/* Interfaces for test purposes. */
import "ocidl.idl";


[object,
  oleautomation,
  uuid(69B1A795-7579-4DAC-8FC9-72D410E346D3),
  helpstring("Callback interface for testing bidirectional communication.")]
interface ICalcCb : IUnknown {
    [helpstring("Process message.")]
    HRESULT Message([in,string] BSTR message);
};

[ object,
  oleautomation,
  uuid(9E91B361-831F-4857-82F7-347A8592C70B),
  helpstring("Initial interface.")]
interface ICalc : IUnknown {
    [helpstring("Get magic value.")]
    HRESULT GetValue ([out,retval] int * value);
};

[ object,
  oleautomation,
  uuid(37368275-D3C9-48B0-9F75-781531E6E719),
  helpstring("Derived interface with aditional method(s).")]
interface ICalcExt : ICalc {
    [helpstring("Add two values.")]
    HRESULT Add ([in] int a, [in] int b, [out,retval] int * result);

    [helpstring("Set callback object.")]
    HRESULT SetCallback([in] ICalcCb * cb);
};

[ object,
  oleautomation,
  uuid(D8AC9315-CE17-4268-911F-18F5F2135B7F),
  helpstring("Newer interface. For testing of multiple inheritance.")]
interface ICalc2 : IUnknown {
    [helpstring("Get magic value.")]
    HRESULT GetValue2 ([out,retval] int * value);
};


[uuid(797C7C01-88F4-4794-AA1C-ACD612BE9AF4),
version(1.0),
helpstring("Example type library.")]
library TestInterfaces {
    interface ICalcCb;
    interface ICalc;
    interface ICalcExt;
    interface ICalc2;
};
